Release 1.5.0 (#24)

diff --git a/net.mkiol.SpeechNote.Addon.amd.yaml b/net.mkiol.SpeechNote.Addon.amd.yaml
--- a/net.mkiol.SpeechNote.Addon.amd.yaml
+++ b/net.mkiol.SpeechNote.Addon.amd.yaml
@@ -1,7 +1,7 @@
 id: net.mkiol.SpeechNote.Addon.amd
 runtime: net.mkiol.SpeechNote
 runtime-version: beta
-sdk: org.kde.Sdk//5.15-24.08
+sdk: org.kde.Sdk//6.11
 build-extension: true
 build-options:
   no-debuginfo: true
@@ -23,7 +23,7 @@ modules:
         cd ${FLATPAK_DEST}
         ln -s ${FLATPAK_DEST}/extra/rocm rocm
     sources:
-      - rocm-deb-sources.yaml
+      - rocm-deb-sources-7.2.4.yaml
 
   - name: python3-pybind11
     only-arches:
@@ -31,16 +31,16 @@ modules:
     buildsystem: simple
     cleanup:
       - /bin
-      - /lib/python3.12/site-packages/pybind11*
+      - /lib/python3.13/site-packages/pybind11*
     build-commands:
       - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
         --prefix=${FLATPAK_DEST} "pybind11" --no-build-isolation
     sources:
       - type: file
-        url: https://files.pythonhosted.org/packages/06/55/9f73c32dda93fa4f539fafa268f9504e83c489f460c380371d94296126cd/pybind11-2.11.1-py3-none-any.whl
-        sha256: 33cdd02a6453380dd71cc70357ce388ad1ee8d32bd0e38fc22b273d050aa29b3
+        url: https://files.pythonhosted.org/packages/b3/06/c3a23c9a0263b136c519f033a58d4641e73065fefc7754e9667ec206d992/pybind11-3.0.4-py3-none-any.whl
+        sha256: 961720ee652da51d531b7b2451a6bd2bc042b0106e6d9baa48ecb7d58034ce63
 
-  # Due to the limitations of the Flathub infrastructure, it is not possible to build CUDA version of ctranslate2 and whisper.cpp.
+  # Due to the limitations of the Flathub infrastructure, it is not possible to build ROCm version of ctranslate2 and whisper.cpp.
   # To overcome this problem, pre-compiled binaries from https://github.com/mkiol/dsnote are installed.
   - name: precompiled-binaries
     only-arches:
@@ -48,7 +48,7 @@ modules:
     buildsystem: simple
     build-options:
       env:
-        PYTHONPATH: /app/extensions/amd/lib/python3.12/site-packages:/app/lib/python3.12/site-packages
+        PYTHONPATH: /app/extensions/amd/lib/python3.13/site-packages:/app/lib/python3.13/site-packages
     cleanup:
       - /bin
     build-commands:
@@ -57,15 +57,13 @@ modules:
       - |
         set -e
         cd ${FLATPAK_DEST}/lib
-        ln -s libctranslate2.so.4.3.1 libctranslate2.so.4
-        ln -s libctranslate2.so.4.3.1 libctranslate2.so
-        ln -s libwhisper-hipblas.so.1.7.1 libwhisper-hipblas.so.1
-        ln -s libwhisper-hipblas.so.1.7.1 libwhisper-hipblas.so
+        ln -s libctranslate2.so.4.8.1 libctranslate2.so.4
+        ln -s libctranslate2.so.4.8.1 libctranslate2.so
     sources:
       - type: archive
         strip-components: 0
-        url: https://github.com/mkiol/dsnote/releases/download/b4.8.0-4/flatpak_binaries_amd_1_4.tar.xz
-        sha256: 613052dd941962ade839214da8a894e81fbb748686964a491d4b4fd2de7547c6
+        url: https://github.com/mkiol/dsnote/releases/download/b4.9.1-1/flatpak_binaries_amd_1_5.tar.xz
+        sha256: 5b7fd8e31d0f0a41159ceb18c84b26ff705a5f4b3a7738e3eb36115a8d1b6b7f
 
   - name: python3-torch-rocm
     only-arches:
@@ -73,153 +71,130 @@ modules:
     buildsystem: simple
     build-options:
       env:
-        PYTHONPATH: /app/extensions/amd/lib/python3.12/site-packages:/app/lib/python3.12/site-packages
-    cleanup:
-      - /bin
+        PYTHONPATH: /app/extensions/amd/lib/python3.13/site-packages:/app/lib/python3.13/site-packages
     build-commands:
       - |
         set -e
-        mkdir -p ${FLATPAK_DEST}/lib/python3.12/site-packages
-        cd ${FLATPAK_DEST}/lib/python3.12/site-packages
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torch torch
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torch-2.5.1+rocm6.2.dist-info torch-2.5.1+rocm6.2.dist-info
-        ln -s ${FLATPAK_DEST}/extra/site-packages/functorch functorch
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torchgen torchgen
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torchaudio torchaudio
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torchaudio-2.5.1+rocm6.2.dist-info torchaudio-2.5.1+rocm6.2.dist-info
-        ln -s ${FLATPAK_DEST}/extra/site-packages/torio torio
-        ln -s ${FLATPAK_DEST}/extra/site-packages/triton triton
-        ln -s ${FLATPAK_DEST}/extra/site-packages/pytorch_triton_rocm-3.1.0.dist-info pytorch_triton_rocm-3.1.0.dist-info
+        libs=(torch torch-2.12.0+rocm7.2.dist-info functorch torchgen
+              torchaudio torchaudio-2.11.0+rocm7.2.dist-info
+              triton triton_rocm-3.6.0.dist-info torio)
+        src_dir="${FLATPAK_DEST}/extra/site-packages"
+        trg_dir="${FLATPAK_DEST}/lib/python3.13/site-packages"
+        mkdir -p "${trg_dir}"
+        cd "${trg_dir}"
+        for lib in "${libs[@]}"; do
+          ln -s "${src_dir}/${lib}" ${lib}
+        done
     sources:
       - type: extra-data
-        url: https://download.pytorch.org/whl/rocm6.2/torch-2.5.1%2Brocm6.2-cp312-cp312-linux_x86_64.whl
-        sha256: 80c7af931acb3941530a717aaa1d142985ae7f29b7660a72e47f1a890fc191fb
+        url: https://download-r2.pytorch.org/whl/rocm7.2/torch-2.12.0%2Brocm7.2-cp313-cp313-manylinux_2_28_x86_64.whl
+        sha256: 58c07e4cc60c1c47d96bbffb9222f47c1090fc5dea8d9418146d2508a87b785e
         filename: torch.whl
-        size: 3973485108
+        size: 6177018819
       - type: extra-data
-        url: https://download.pytorch.org/whl/pytorch_triton_rocm-3.1.0-cp312-cp312-linux_x86_64.whl
-        sha256: 3b56b87886d03dcf3aeb8f78f372f5da60b29ffdffcba5cd767b4bfdec47175b
-        filename: triton.whl
-        size: 344817184
-      - type: extra-data
-        url: https://download.pytorch.org/whl/rocm6.2/torchaudio-2.5.1%2Brocm6.2-cp312-cp312-linux_x86_64.whl
-        sha256: 63d1cfe70d8fb6154d85b5b44dbd055587828fc260c2f86cf924433ca897b917
+        url: https://download-r2.pytorch.org/whl/rocm7.2/torchaudio-2.11.0%2Brocm7.2-cp313-cp313-manylinux_2_28_x86_64.whl
+        sha256: 9228e1c534d04d80fa7b46205f448da947fd06f5573ba8602f041b504edb3596
         filename: torchaudio.whl
-        size: 1730067
+        size: 337774
+      - type: extra-data
+        url: https://download-r2.pytorch.org/whl/triton_rocm-3.6.0-cp313-cp313-linux_x86_64.whl
+        sha256: d43b44f045d7f78d1dfe03b2debce36e0d756041a853633a2677ce5a890a269e
+        filename: triton_rocm.whl
+        size: 302485249
 
-  - name: suitesparse
-    buildsystem: cmake-ninja
-    config-opts:
-      - -DBUILD_STATIC_LIBS=OFF
-      - -DBUILD_SHARED_LIBS=ON
-      - -DSUITESPARSE_ENABLE_PROJECTS=cholmod;amd;colamd;cxsparse
-    cleanup:
-      - /bin
-      - /include
-      - /lib/cmake
-      - /lib/debug
-      - /lib/*.a
-      - /lib/*.la
-      - /lib/pkgconfig
-      - /share/man
-    sources:
-      - type: git
-        url: https://github.com/DrTimothyAldenDavis/SuiteSparse.git
-        tag: v7.8.3
-        commit: d3c4926d2c47fd6ae558e898bfc072ade210a2a1
-
-  - name: apply-extra-amd
+  - name: apply-extra-script
     only-arches:
       - x86_64
     buildsystem: simple
     build-commands:
       - install -Dm755 apply_extra ${FLATPAK_DEST}/bin/apply_extra
       - install -Dm755 /usr/bin/ar ${FLATPAK_DEST}/bin/ar
-      - install -Dm644 /usr/lib/x86_64-linux-gnu/libsframe.so.1 ${FLATPAK_DEST}/lib/libsframe.so.1
-      - install -Dm644 /usr/lib/x86_64-linux-gnu/libbfd-2.44.so ${FLATPAK_DEST}/lib/libbfd-2.44.so
+      - install -Dm644 /usr/lib/x86_64-linux-gnu/libsframe.so.3 ${FLATPAK_DEST}/lib/libsframe.so.3
+      - install -Dm644 /usr/lib/x86_64-linux-gnu/libbfd-2.46.so ${FLATPAK_DEST}/lib/libbfd-2.46.so
     sources:
       - type: script
         dest-filename: apply_extra
         commands:
           - |
-            set -e
             echo
+            echo "Files to install:"
+            ls
+          - |
+            set -e
+            extra_dir="/app/extra"
+            trg_dir="${extra_dir}/rocm"
+            tmp_dir="${extra_dir}/rocm_tmp"
+
             echo "Installing ROCm..."
-            mkdir -p rocm_tmp
+            mkdir -p "${tmp_dir}"
             for f in *.deb; do
-              mv "$f" rocm_tmp/
+              mv "$f" "${tmp_dir}/"
             done
-            cd rocm_tmp
+            cd "${tmp_dir}"
             for f in *.deb; do
+              echo "Installing ${f}..."
               tmp="${f}_tmp"
               mkdir -p "$tmp"
               mv "$f" $tmp/
               cd "$tmp"/
               ar x "$f"
-              rm -rf "$f"
+              rm -f "$f"
               tar -xf data.tar.* -C ../ --no-same-owner --no-same-permissions
               cd ..
               rm -rf "$tmp"
             done
-            mv -T opt/rocm-* ../rocm
-            cd ..
-            rm -rf rocm_tmp
-            rm -rf rocm/bin
-            rm -rf rocm/hip*
-            rm -rf rocm/hsa
-            rm -rf rocm/roc*
-            rm -rf rocm/miopen*
-            rm -rf rocm/rccl*
-            rm -rf rocm/oam
-            rm -rf rocm/share/doc
-            rm -rf rocm/share/dec
-            rm -rf rocm/share/hip
-            rm -rf rocm/share/hipfort
-            rm -rf rocm/share/html
-            rm -rf rocm/share/rccl
-            rm -rf rocm/share/rocm
-            rm -rf rocm/share/miopen/perf_models
-            rm -rf rocm/share/openmp-extras
-            rm -rf rocm/share/rocmcmakebuildtools
-            rm -rf rocm/share/rocprofiler*
-            rm -rf rocm/share/modulefiles
-            rm -rf rocm/.info
-            rm -rf rocm/include
-            rm -rf rocm/opencl
-            rm -rf rocm/lib/libOpenCL.so*
-            rm -rf rocm/lib/cmake
-            rm -rf rocm/lib/rocmmod
-            rm -rf rocm/lib/CMakeFiles
-            rm -rf rocm/lib/llvm/lib-debug
-            rm -rf rocm/lib/llvm/share
-            rm -rf rocm/libexec
-            rm -rf rocm/llvm
-            for f in $(find rocm/ -name "*.a"); do
+            mv -T opt/rocm-* "${trg_dir}"
+            cd "${extra_dir}"
+            rm -r "${tmp_dir}"
+
+            # cleanup
+            paths=(.info bin share/amd* share/doc share/dec share/hip share/hipfort share/html
+                   share/info share/man share/mivisionx share/modulefiles share/openmp-extras
+                   share/pkgconfig share/rccl share/rdhc share/rocdecode share/rocgdb share/rocjpg
+                   share/rocm* share/rocprofiler* share/rocmcmakebuildtools share/modulefiles 
+                   lib/libOpenCL.so* lib/cmake lib/rocmmod lib/CMakeFiles lib/llvm/lib-debug 
+                   lib/llvm/share lib/python* libexec llvm include)
+            for path in "${paths[@]}"; do
+              rm -rf "${trg_dir}/"${path}
+            done
+            for f in $(find "$trg_dir" -name "*.a"); do
               rm -f "$f"
+            done
+
+            # create missing links
+            cd "${trg_dir}/lib"
+            for lib in *.so.[0-9]*; do
+              if [[ -f "$lib" ]]; then
+                  target="${lib%.*}"
+                  if [[ ! -e "$target" ]]; then
+                      ln -s "$lib" "$target"
+                  fi
+              fi
             done
           - |
             set -e
+            extra_dir="/app/extra"
+            trg_dir="${extra_dir}/site-packages"
             echo "Installing PyTorch..."
-            mkdir -p site-packages
-            cd site-packages
-            unzip -q ../torch.whl
-            rm -rf ../torch.whl
-            rm -rf torch/include
-            unzip -q ../triton.whl
-            rm -rf ../triton.whl
-            unzip -q ../torchaudio.whl
-            rm -rf ../torchaudio.whl
-            rm -rf torch/lib/rocblas
-            rm -rf torch/lib/libamd*
-            rm -rf torch/lib/libroc*
-            rm -rf torch/lib/libhip*
-            rm -rf torch/lib/libhsa*
-            rm -rf torch/lib/libMIOpen*
-            rm -rf torch/lib/librccl*
-            rm -rf torch/lib/libnuma*
-            rm -rf torch/lib/hipblas*
-            rm -rf torch/lib/msccl-algorithms
-            rm -rf torch/include
+            libs=(torch torchaudio triton_rocm)
+            mkdir -p "${trg_dir}"
+            cd "${trg_dir}"
+            for lib in "${libs[@]}"; do
+              echo "Installing ${lib}.whl..."
+              unzip -q ../${lib}.whl
+              rm -rf ../${lib}.whl
+            done
+
+            # cleanup
+            paths=(torch/lib/rocblas torch/lib/libamd* torch/lib/libroc* torch/lib/libhip*
+                   torch/lib/libhsa* torch/lib/libMIOpen* torch/lib/librccl* torch/lib/libnuma*
+                   torch/lib/hipblas* torch/lib/msccl-algorithms torch/include)
+            for path in "${paths[@]}"; do
+              rm -rf ${path}
+            done
+            for f in $(find . -name "*.a"); do
+              rm -f "$f"
+            done
 
   - name: metadata
     buildsystem: simple
